title: JG's Blog
description: > # this means to ignore newlines until "baseurl:"
  Hello myblog!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jack Grence # add your name
author-img: miigo.jpg # add your photo
about-author: Hello! I'm the pwner of this blog :p # add description
twitter: NULL # add your Twitter handle
facebook: NULL # add your Facebook handle
github: jackgrence # add your Github handle
linkedin: NULL # add your Linkedin handle
email: NULL # add your Email address

# Disqus
discus-identifier: jgblog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
